apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: development
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 256Mi
        cpu: 0.5
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest-without-limit
  namespace: development
spec:
  containers:
    - name: nginx
      image: nginx:alpine
