apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels:
    name: stage
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-stage
  namespace: stage
spec:
  limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100Mi
        cpu: 0.5
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest-with-min-max
  namespace: stage
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        limits:
          memory: 500M
          cpu: 1
        requests:
          memory: 400M
          cpu: 0.5
